### ISSUE TITLE
Issue with compiled kernel modules.

### ISSUE THREAD

**Issue by stenh0use** [slushie/docker-module-builder#1]
I stumbled upon your idea for compiling kernel modules for docker for mac and its awesome, its absolutely killing that docker for mac does not have proper kernel module support for networking.

trying to compile `ip_vs` and `nf_conntrack_ipv4` but not having much luck.

I end up with this error:

```
insmod net/netfilter/ipvs/ip_vs.ko 
insmod: can't insert 'net/netfilter/ipvs/ip_vs.ko': invalid module format
```

My end compiled kernel modules don't seem to work. Any hints or help on what I need to do to compile a module that will be accepted by docker would be greatly appreciated.

I've tried this on both docker for mac v2.2.0.5 (this one still has SCTP :)) and the latest v2.3.0.4

I've tried from both downloading the kernel source and also using the included source within the docker container. My last attempt went something like this.

```
docker run --privileged  -itd -v $PWD:/data --entrypoint "/bin/sh" kernel-module:latest

cd /usr/src/linuxkit
tar xf linux.tar.xz  -C /tmp/
cd /tmp/linux/
cp /data/.config .
make modules_prepare
cp  /usr/src/linux-headers-$(uname -r)/Module.symvers .
make M=net/netfilter
insmod net/netfilter/ipvs/ip_vs.ko 
```

**Comment by slushie** [comment]
`Invalid module format` is usually due to mismatched kernel or gcc versions. You can't use the upstream kernel, since the kernel in the VM is patched. And unfortunately, the kernel sources may change with every Docker Desktop release. So it might work for you, but not for your users.

If you can get the `linuxkit.yml` you're half-way there. It will list the image with kernel sources. Check out the `Makefile` in this repo, there is a `make linuxkit.yml` target that will fetch it for you. If you don't want to use the `Dockerfile` to build your module, you can follow the steps in there to get the kernel sources unpacked. 

Once you have the sources, it should be pretty straightforward. Just make sure you build with the right gcc version! `docker run --rm alpine cat /proc/version` will tell you that. For me that shows `gcc version 8.3.0 (Alpine 8.3.0)` which is [included with Alpine 3.10](https://pkgs.alpinelinux.org/packages?name=gcc&branch=v3.10). So `alpine:3.10` is a good image to use to build the module.

Good luck! 🤞

**Comment by stenh0use** [comment]
Hey thank you so much for the reply, I really appreciate this as I am scratching my head a little but. So In all cases I have used your Makefile to create the base docker container, I just reduced it to the following whilst I figured out how to compile the modules.

```
ARG KERNEL_REF
ARG BUILD_REF

FROM ${KERNEL_REF} as kernel-source
FROM ${BUILD_REF} as build

# unpack kernel sources
WORKDIR /usr/src/linuxkit
COPY --from=kernel-source / .
RUN tar xf kernel-dev.tar -C /
RUN tar xf kernel.tar -C /

# install dependencies
RUN apk add -U build-base git curl perl
```

I could not figure out how to compile a linux kernel module that works. I tried compiling using the following `make -C /usr/src/linux-headers-$(uname -r) M=/path/to/modules` but ran into to missing header files that I could not resolve.

Do you have an example of that you could share for how you compiled `wireguard`

Following this guys docker file I managed to compile some kernel modules within the netfilter family, but unfortunately not the one I was after wouldn't load. 

```shell
make build 
docker run --rm --privileged --name kernel -itd --entrypoint "/bin/sh" kernel-module:latest 
docker exec -it kernel sh

tar xf linux.tar.xz -C /usr/src/

apk update && apk add argp-standalone automake bash bc binutils-dev bison build-base curl diffutils flex git gmp-dev gnupg installkernel kmod elfutils-dev 
linux-headers mpc1-dev mpfr-dev ncurses-dev openssl-dev patch sed squashfs-tools tar xz xz-dev zlib-dev

echo "CONFIG_IP_VS=m" >> /usr/src/linux-headers-$(uname -r)/.config
cd ../linux
cp ../linux-headers-$(uname -r)/.config ../linux-headers-$(uname -r)/Module.symvers .
cp ../linux-headers-$(uname -r)/scripts/gcc-plugins/randomize_layout_seed.h scripts/gcc-plugins/randomize_layout_seed.h
mkdir include/generated 
cp ../linux-headers-$(uname -r)/include/generated/randomize_layout_hash.h include/generated/randomize_layout_hash.h
make olddefconfig
make modules_prepare
make M=net/netfilter/ipvs
make -j 4 M=net/netfilter
```

So after this ran I was able to load two modules, but not the one I was after. The ip_vs module info looks a bit strange, the param section was set in the config to 12 bits by default.
```shell
/usr/src/linux # modinfo net/netfilter/ipvs/ip_vs.ko
filename:       /usr/src/linux/net/netfilter/ipvs/ip_vs.ko
license:        GPL
depends:        
retpoline:      Y
name:           ip_vs
vermagic:       4.19.76-linuxkit SMP mod_unload modversions RANDSTRUCT_PLUGIN_89fd6963260b95cbe404fe80b215c0749354ebbf0a1ea296a6f33805c9ea1da9
parm:           conn_tab_bits:Set connections' hash size (int)

/usr/src/linux # insmod net/netfilter/ipvs/ip_vs.ko
insmod: ERROR: could not insert module net/netfilter/ipvs/ip_vs.ko: Invalid module format
/usr/src/linux # modinfo net/netfilter/xt_ipvs.ko
filename:       /usr/src/linux/net/netfilter/xt_ipvs.ko
alias:          ip6t_ipvs
alias:          ipt_ipvs
license:        GPL
description:    Xtables: match IPVS connection properties
author:         Hannes Eder <heder@google.com>
depends:        ip_vs
retpoline:      Y
name:           xt_ipvs
vermagic:       4.19.76-linuxkit SMP mod_unload modversions RANDSTRUCT_PLUGIN_89fd6963260b95cbe404fe80b215c0749354ebbf0a1ea296a6f33805c9ea1da9

/usr/src/linux # insmod net/netfilter/xt_ipvs.ko
/usr/src/linux # lsmod |grep xt_ipvs
xt_ipvs                16384  0

/usr/src/linux # insmod net/netfilter/nft_fib.ko
lsmod |grep fib
nft_fib                16384  0
```

I was able to compile SCTP but loading it into the kernel causes docker to crash.
```
echo "CONFIG_IP_SCTP=m" >> .config
make olddefconfig
make modules_prepare
make M=net/sctp

/usr/src/linux # modinfo net/sctp/sctp.ko
filename:       /usr/src/linux/net/sctp/sctp.ko
license:        GPL
description:    Support for the SCTP protocol (RFC2960)
author:         Linux Kernel SCTP developers <linux-sctp@vger.kernel.org>
alias:          net-pf-10-proto-132
alias:          net-pf-2-proto-132
depends:        
retpoline:      Y
name:           sctp
vermagic:       4.19.76-linuxkit SMP mod_unload modversions RANDSTRUCT_PLUGIN_89fd6963260b95cbe404fe80b215c0749354ebbf0a1ea296a6f33805c9ea1da9
parm:           no_checksums:Disable checksums computing and verification (bool)
/usr/src/linux # insmod /usr/src/linux/net/sctp/sctp.ko
Error response from daemon: Bad response from Docker engine
```
![Screen Shot 2020-08-27 at 6 15 10 pm](https://user-images.githubusercontent.com/5916243/91415433-6162fa80-e891-11ea-8365-57cd625f2b44.png)

**Comment by slushie** [comment]
You're probably missing the kernel config from the build. Since you're building out-of-tree, don't copy those files in just make sure you use the `build` directory rather than the `linux-headers-XXX` directory. The [kernel docs](https://www.kernel.org/doc/Documentation/kbuild/modules.txt) describe out-of-tree builds, you'd use: `$ make -C /lib/modules/`uname -r`/build M=$PWD` where `$PWD` is your module's source directory.

For wireguard as an example, I cloned the module source code under the `module` directory of this repo. Then I set up a short `module/Makefile` that builds and copies the resulting `.ko` back out.

Here's my `Makefile`:
```
all: build wireguard.ko

build:
	make -C wireguard-linux-compat/src

wireguard.ko:
	cp -a wireguard-linux-compat/src/wireguard.ko .
```

Wireguard itself is building the same way as the kernel docs recommend: 

```
module:
	@$(MAKE) -C $(KERNELDIR) M=$(PWD) WIREGUARD_VERSION="$(WIREGUARD_VERSION)" modules
```
(thats from wireguard upstream https://git.zx2c4.com/wireguard-linux-compat)
Where `KERNELDIR=/lib/modules/$(uname -r)/build`


Here's my directory structure:
```
❯ tree -L 3
.
├── Dockerfile
├── LICENSE
├── Makefile
├── README.md
├── linuxkit.yml
└── module
    ├── Makefile # this Makefile I wrote to build the module and copy the .ko
    └── wireguard-linux-compat
        ├── COPYING
        ├── README.md
        ├── kernel-tree-scripts
        └── src # contains the module source code itself, plus a Makefile
```

**Comment by stenh0use** [comment]
I really have to say thanks once again for your detailed response and help.

I definitely did try earlier using the kernel source and doing out of tree build, but I was not able to get the compiler to action on the modules. I tried again today, and have provided the makefile which integrates with your makefile/Dockerfile. I managed to get the module to build by adding `obj-m+=ip_vs.o` to the variables within the build scripts.

```
all: build ip_vs.ko

build:
	tar xf /usr/src/linuxkit/linux.tar.xz -C /usr/src/
	make -C /lib/modules/`uname -r`/build M=/usr/src/linux/net/netfilter/ipvs obj-m+=ip_vs.o

ip_vs.ko:
	cp -a /usr/src/linux/net/netfilter/ipvs/ip_vs.ko .
```

```
Step 12/15 : RUN make -C module
 ---> Running in 6dc765bac7dd
make: Entering directory '/usr/src/module'
tar xf /usr/src/linuxkit/linux.tar.xz -C /usr/src/
make -C /lib/modules/`uname -r`/build M=/usr/src/linux/net/netfilter/ipvs obj-m+=ip_vs.o
make[1]: Entering directory '/usr/src/linux-headers-4.19.76-linuxkit'
  CC [M]  /usr/src/linux/net/netfilter/ipvs/ip_vs_conn.o
  CC [M]  /usr/src/linux/net/netfilter/ipvs/ip_vs_core.o
  CC [M]  /usr/src/linux/net/netfilter/ipvs/ip_vs_ctl.o
  CC [M]  /usr/src/linux/net/netfilter/ipvs/ip_vs_sched.o
  CC [M]  /usr/src/linux/net/netfilter/ipvs/ip_vs_xmit.o
  CC [M]  /usr/src/linux/net/netfilter/ipvs/ip_vs_app.o
  CC [M]  /usr/src/linux/net/netfilter/ipvs/ip_vs_sync.o
  CC [M]  /usr/src/linux/net/netfilter/ipvs/ip_vs_est.o
  CC [M]  /usr/src/linux/net/netfilter/ipvs/ip_vs_proto.o
  CC [M]  /usr/src/linux/net/netfilter/ipvs/ip_vs_pe.o
  CC [M]  /usr/src/linux/net/netfilter/ipvs/ip_vs_proto_tcp.o
  CC [M]  /usr/src/linux/net/netfilter/ipvs/ip_vs_proto_udp.o
  CC [M]  /usr/src/linux/net/netfilter/ipvs/ip_vs_proto_ah_esp.o
  CC [M]  /usr/src/linux/net/netfilter/ipvs/ip_vs_nfct.o
  CC      /usr/src/linux/net/netfilter/ipvs/ip_vs_rr.o
  CC      /usr/src/linux/net/netfilter/ipvs/ip_vs_wrr.o
  CC      /usr/src/linux/net/netfilter/ipvs/ip_vs_lc.o
  CC      /usr/src/linux/net/netfilter/ipvs/ip_vs_wlc.o
  CC      /usr/src/linux/net/netfilter/ipvs/ip_vs_fo.o
  CC      /usr/src/linux/net/netfilter/ipvs/ip_vs_ovf.o
  CC      /usr/src/linux/net/netfilter/ipvs/ip_vs_lblc.o
  CC      /usr/src/linux/net/netfilter/ipvs/ip_vs_lblcr.o
  CC      /usr/src/linux/net/netfilter/ipvs/ip_vs_dh.o
  CC      /usr/src/linux/net/netfilter/ipvs/ip_vs_sh.o
  CC      /usr/src/linux/net/netfilter/ipvs/ip_vs_mh.o
  CC      /usr/src/linux/net/netfilter/ipvs/ip_vs_sed.o
  CC      /usr/src/linux/net/netfilter/ipvs/ip_vs_nq.o
  CC      /usr/src/linux/net/netfilter/ipvs/ip_vs_ftp.o
  AR      /usr/src/linux/net/netfilter/ipvs/built-in.a
  LD [M]  /usr/src/linux/net/netfilter/ipvs/ip_vs.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /usr/src/linux/net/netfilter/ipvs/ip_vs.mod.o
  LD [M]  /usr/src/linux/net/netfilter/ipvs/ip_vs.ko
```

The module looks good but still doesn't want to load.
```
/usr/src # modinfo module/ip_vs.ko 
filename:       module/ip_vs.ko
license:        GPL
parm:           conn_tab_bits:Set connections' hash size
depends:        
vermagic:       4.19.76-linuxkit SMP mod_unload modversions RANDSTRUCT_PLUGIN_89fd6963260b95cbe404fe80b215c0749354ebbf0a1ea296a6f33805c9ea1da9
/usr/src # insmod module/ip_vs.ko 
insmod: can't insert 'module/ip_vs.ko': invalid module format
```

 I think I will probably give up and look at docker-machine/vanilla linux as doesn't look like I am having much luck 😞

**Comment by slushie** [comment]
Hi @spookiej I had a chance to reproduce your steps and managed to run into the same problem as you. But I think I've discovered the cause. It looks like `ip_vs` is already built into the kernel, not as a module. 

```
/usr/src/linux-headers-4.19.76-linuxkit # grep CONFIG_IP_VS= .config
CONFIG_IP_VS=y
```

So the `invalid module format` is misleading here, it just can't be loaded because the functionality should already be provided by the kernel -- I think there will be symbol conflicts (since the kernel already has this code). But if it doesn't have the options you need, you're out of luck because the options are compiled into the kernel. So if it doesn't work for you as-is, you'd have to rebuild the kernel. In which case, docker-machine might be a better solution.

**Comment by stenh0use** [comment]
Hey @slushie, thanks for looking further into this. I guess this makes sense, I looked into the `.config` and sctp is not compiled into the kernel, so it should be in theory compilable, although i ran into issues so I am just going to park it for now. The other option is to use linuxkit to create a whole new VM for docker,  but looks like it might take me a weekend to figure out.

**Comment by adibrastegarnia** [comment]
@spookiej 
Do you have a solution for loading sctp module for Docker? That would be great if you share it with me.

**Comment by stenh0use** [comment]
hey @adibrastegarnia no solution that I have entailed, I just rolled back to the previous docker for mac version that included the sctp library.

I think options are:
1. build your own moby docker for mac image
2. try docker-machine
3. use the old version of docker for mac that has it included.

**Comment by adibrastegarnia** [comment]
@spookiej 
Thanks for your response. I will give them a try.

**Comment by adibrastegarnia** [comment]
@spookiej 
BTW, what version of docker you are using for that purpose?

**Comment by stenh0use** [comment]
I think it is v2.2.0.5

**Comment by adibrastegarnia** [comment]
@spookiej 
Thanks

**Comment by stenh0use** [comment]
@adibrastegarnia I don't know if you ended up sorting out your kernel problem or not, but I made a [docker-machine based project](https://github.com/spookiej/docker-machine-for-mac) to make custom docker machines almost as easy as docker for mac.
